language: ruby
sudo: required
dist: trusty
script: rake
rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - ruby-head
  - jruby
  - jruby-head
  - jruby-19mode
  - rubinius-3

before_install:
  - "gem install bundler"

matrix:
  allow_failures:
    - rvm: "ruby-head"
    - rvm: "jruby-head"
